language: bash

dist: trusty

sudo: required

env:
    - INIT=openrc

before_install:
#    - mount
#    - ls -la /dev/shm
     - echo $TRAVIS_COMMIT_RANGE
     - echo $INIT

#install:
    #- .travis/scripts/install_dependencies.sh
    #- .travis/scripts/setup_pacman.sh
    #- .travis/scripts/setup_manjaro_tools.sh

before_script:
    - .travis/scripts/changed_packages.sh $TRAVIS_COMMIT_RANGE || travis_terminate 0  # nothing to do if no package changed
    - .travis/scripts/setup_build_environment.sh $INIT

script:
    #- .travis/scripts/build_packages.sh
    - .travis/scripts/build_packages_in_chroot.sh $TRAVIS_COMMIT_RANGE $INIT

after_script:
    - ls $HOME/manjaro-chroot/var/cache/manjaro-tools/pkg/unstable/x86_64

notifications:
    email: false
