language: bash

dist: trusty

sudo: required

#before_install: true

#install:
        #- scripts/install_dependencies.sh
        #- scripts/setup_pacman.sh
        #- scripts/setup_manjaro_tools.sh

before_script:
        - scripts/changed_packages.sh || travis_terminate 0  # nothing to do if no package changed
        - scripts/setup_build_environment.sh

script:
        #- scripts/build_packages.sh
        - mount
        - scripts/build_packages_in_a_chroot.sh

notifications:
        email: false
