language: bash

dist: trusty

sudo: required

before_install:
        - mount
        - ls -la /dev/shm

#install:
        #- scripts/install_dependencies.sh
        #- scripts/setup_pacman.sh
        #- scripts/setup_manjaro_tools.sh

before_script:
        - scripts/changed_packages.sh || travis_terminate 0  # nothing to do if no package changed
        - scripts/setup_build_environment.sh

script:
        #- scripts/build_packages.sh
        - scripts/build_packages_in_chroot.sh

after_script:
        - ls $HOME/manjaro-chroot/var/cache/manjaro-tools/pkg/unstable/x86_64

notifications:
        email: false
