language: bash

dist: trusty

sudo: required

#before_install: true

install:
        - scripts/install_dependencies.sh
        - scripts/setup_pacman.sh
        - scripts/setup_manjaro_tools.sh

before_script:
        - scripts/setup_build_environment.sh
        - scripts/changed_packages.sh

script:
        - scripts/build_packages.sh

notifications:
        email: false
